# Generated by Django 4.2.4 on 2023-08-16 03:14

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sunday', models.CharField(blank=True, max_length=11, null=True)),
                ('monday', models.CharField(blank=True, max_length=11, null=True)),
                ('tuesday', models.CharField(blank=True, max_length=11, null=True)),
                ('wednesday', models.CharField(blank=True, max_length=11, null=True)),
                ('thursday', models.CharField(blank=True, max_length=11, null=True)),
                ('friday', models.CharField(blank=True, max_length=11, null=True)),
                ('saturday', models.CharField(blank=True, max_length=11, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NightTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sunday', models.CharField(blank=True, max_length=11, null=True)),
                ('monday', models.CharField(blank=True, max_length=11, null=True)),
                ('tuesday', models.CharField(blank=True, max_length=11, null=True)),
                ('wednesday', models.CharField(blank=True, max_length=11, null=True)),
                ('thursday', models.CharField(blank=True, max_length=11, null=True)),
                ('friday', models.CharField(blank=True, max_length=11, null=True)),
                ('saturday', models.CharField(blank=True, max_length=11, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('reviews', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lomito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('maps', models.URLField(null=True)),
                ('logo', models.ImageField(null=True, upload_to=api.models.lomito_directory_path)),
                ('day_time', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.daytime')),
                ('night_time', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.nighttime')),
                ('rating', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.rating')),
            ],
        ),
    ]
